<?php

function cipher_menu() {
    $items = array();
    $items['encrypt'] = array(
            'title' => 'Encrypt',
            'type' => MENU_NORMAL_ITEM,
            'access callback' => TRUE,
            'page callback' => 'drupal_get_form',
            'page arguments' => array('encrypt_form'),
        );
    $items['encrypt_success'] = array(
            'title' => 'Your Encrypted Phrase',
            'type' => MENU_CALLBACK,
            'access callback' => true,
            'page callback' => 'encrypt_success',
        );
    $items['decrypt'] = array(
            'title' => 'Original Phrase Details',
            'type' => MENU_CALLBACK,
            'access callback' => TRUE,
            'page callback' => 'decrypt',
        );
    return $items;
}

// form and form_submit hooks
function decrypt_button_form() {
    $form = array();
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Decrypt This Phrase',
    );
    return $form;
}

function decrypt_button_form_submit($form, &$form_state) {
    $form_state['redirect'] = 'decrypt';
}

function encrypt_form() {
    $form = array();
    $form['value'] = array(
        '#type' => 'textfield',
        '#title' => 'Shift Value',
        '#description' => 'Enter a positive integer',
        '#element_validate' => array('element_validate_integer_positive'),
        '#attributes' => array('placeholder' => array('Leave blank to assign a random shift value')),
    );
    $form['direction'] = array(
        '#type' => 'textfield',
        '#title' => 'Shift Direction',
        '#description' => "Specify 'left' or 'right'",
        '#element_validate' => array('direction_validate'),
        '#attributes' => array('placeholder' => array('Leave blank to assign a random shift direction')),
    );
    $form['phrase'] = array(
        '#type' => 'textfield',
        '#title' => 'Phrase',
        '#description' => 'Enter the phrase you would like to encrypt<br>* Use only letters and approved punctuation: . , ! ? : ; \' "',
        '#element_validate' => array('phrase_validate'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encrypt Phrase',
    );
    return $form;
}

function encrypt_form_submit($form, &$form_state) {
    // if there is no shift value, get one randomly
    $value = $form_state['values']['value'];
    if (!$value) {
        $value = rand(1, 25);
    }
    // if there is no direction, get one randomly
    $direction = $form_state['values']['direction'];
    if (!$direction) {
        if (rand(0, 1)) {
            $direction = 'left';
        } else {
            $direction = 'right';
        }
    }
    $phrase = $form_state['values']['phrase'];
    $encrypted_phrase = encrypt_phrase($value, $direction, $phrase);
    $_SESSION['value'] = $value;
    $_SESSION['direction'] = $direction;
    $_SESSION['phrase'] = $phrase;
    $_SESSION['encrypted phrase'] = $encrypted_phrase;
    $form_state['redirect'] = 'encrypt_success';
}

// validation functions
function phrase_validate($element) {
    $phrase = $element['#value'];
    // find how many characters match the regular expression
    $matching_characters = preg_match_all('/[a-zA-Z ,.!?:;\'\"]/', $phrase);
    if ($matching_characters != strlen($phrase)) {
        form_error($element, t("Your phrase includes unallowed characters."));
    }
}

function direction_validate($element) {
    $direction = $element['#value'];
    $valid_directions = array('left', 'right', '');
    if (!in_array($direction, $valid_directions)) {
        form_error($element, t("Shift Direction invalid. Please enter 'left' or 'right'"));
    }
}

// page templates
function decrypt() {
    $value = $_SESSION['value'];
    $direction = $_SESSION['direction'];
    $phrase = $_SESSION['phrase'];
    $encrypted_phrase = $_SESSION['encrypted phrase'];
    $decrypt_button = drupal_get_form('decrypt_button_form');
    return "
        <p>Original Phrase: $phrase</p>
        <p>Shift Value: $value</p>
        <p>Shift Direction: $direction</p>
        <p>Encrypted Phrase: $encrypted_phrase</p>
    ";
}

function encrypt_success() {
    $encrypted_phrase = $_SESSION['encrypted phrase'];
    $decrypt_button = drupal_get_form('decrypt_button_form');
    return $encrypted_phrase . drupal_render($decrypt_button);
}

// encryption logic
function encrypt_phrase($value, $direction, $phrase) {
    $encrypted_chars = array();
    $phrase_chars = str_split($phrase);
    // if shift loops through the alphabet more than once, cut off the extra
    $modded_value = $value % 26;
    // foreach adjusts characters individually
    foreach($phrase_chars as $char) {
        $char_code = ord($char);
        // define min and max ascii bounds based on whether a character is uppercase or lowercase
        // if character is not a letter, add to the encrypted array and continue to the next iteration of the foreach loop
        $code_min;
        $code_max;
        if ($char_code >= 65 && $char_code <= 90) {
            $code_min = 65;
            $code_max = 90;
        } elseif ($char_code >= 97 && $char_code <= 122) {
            $code_min = 97;
            $code_max = 122;
        } else {
            $encrypted_chars[] = $char;
            continue;
        }
        // adjust character code left or right
        $new_code;
        if ($direction == 'left') {
            $new_code = $char_code - $modded_value;
        } else {
            $new_code = $char_code + $modded_value;
        }
        // correct for overadjustments
        if ($new_code > $code_max) {
            $new_code = ($code_min - 1) + ($new_code - $code_max);
        } elseif ($new_code < $code_min) {
            $new_code = ($code_max + 1) - ($code_min - $new_code);
        }
        // add the new character to the array
        $encrypted_chars[] = chr($new_code);
    }
    return implode($encrypted_chars);
}
